version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hospital_supply
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hospital_network

  # Redis Cache
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - hospital_network

  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/hospital_supply
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGINS=["http://localhost:3000"]
    depends_on:
      - postgres
      - redis
    networks:
      - hospital_network
    volumes:
      - ./backend:/app
      - ./agents:/app/agents

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws
    depends_on:
      - backend
    networks:
      - hospital_network

volumes:
  postgres_data:

networks:
  hospital_network:
    driver: bridge
